project:
  type: website
  output-dir: docs

website:
  title: "epiworldR - Sunbelt 2025 Workshop"
  google-analytics: G-CQNCQM1SG1
  repo-subdir: docs
  repo-url: https://github.com/UofUEpiBio/epiworldR-workshop
  repo-branch: main
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: part1.qmd
        text: "Part 1"
      - href: part2a.qmd
        text: "Part 2a"
      - href: part2b.qmd
        text: "Part 2b"
      - href: part3.qmd
        text: "Part 3"
      - href: examples.qmd
        text: "Additional Learning"

    right: 
      - href: https://github.com/UofUEpiBio/epiworldR-workshop
        text: "GitHub"
        icon: github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: show
    code-link: true
    code-line-numbers: true
    

editor: visual



